language: node_js
node_js:
  - lts/*
env:
  global:
    - CC_TEST_REPORTER_ID=b3fbb2142551bd0794110949748173c18c58aa3466a8c95280b80f4f15b716fb
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make lint
  - make test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
