language: node_js
node_js:
  - lts/*
script:
  - make lint
  - make test
  - make testcoverage
addons:
    code_climate:
        repo_token: b3fbb2142551bd0794110949748173c18c58aa3466a8c95280b80f4f15b716fb
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info